name: Push HEAL Jupyterlab to Quay

on:
  push:
    paths:
      - jupyter-heal/**
      - .github/workflows/build_heal_jupyterlab.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 30000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(echo $(echo ${GITHUB_REF#refs/heads/} | tr / _))"
        id: extract_branch

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: heal-notebooks
          tags: jupyter_lab__${{ github.sha }}
          dockerfiles: ./jupyter-heal/Dockerfile
          build-args: BUILD_DIR=jupyter-heal

      - name: Push To quay.io
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/cdis
          username: ${{ secrets.QUAY_SERVICE_ACCOUNT_USER }}
          password: ${{ secrets.QUAY_SERVICE_ACCOUNT_PASSWORD }}
